spring:
  profiles.active: dev
---
spring:
  application:
    name: web-service
  jpa:
    database: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  datasource:
    postgres:
      url: jdbc:postgresql://localhost:5432/postgres-web-service
      driverClassName: org.postgresql.Driver
  sql:
    init:
      mode: always
